name:             Assets Manager
description:      A Composer plugin to manage "***-assets" package type
meta_description: "Assets Manager - A Composer plugin to manage assets files"
domain_name:      "http://assetsmanager.ateliers-pierrot.fr"

markdown:         redcarpet
highlighter:      pygments
permalink:        /:categories/:title.html
logo:             false
paginate:         10

url:              'http://assetsmanager.ateliers-pierrot.fr'
author:           'Les Ateliers Pierrot'
author_url:       'http://www.ateliers-pierrot.fr/'
homepage:         http://github.com/atelierspierrot/assets-manager
tracker:          http://github.com/atelierspierrot/assets-manager/issues
documentation:    http://assetsmanager.ateliers-pierrot.fr/phpdoc/
license:          GPL-3.0

exclude:
  - bin
  - .git
  - README.md
  - README-kasper.md
include:
  - .htaccess
  - phpdoc

highlight:
  - defaults:
    - lineanchors
    - linenos
    - startinline
