name: Assets Manager
description: A Composer plugin to manage "***-assets" package type
meta_description: "Assets Manager - A Composer plugin to manage assets files"
homepage: http://github.com/atelierspierrot/assets-manager
tracker: http://github.com/atelierspierrot/assets-manager/issues
documentation: http://atelierspierrot.github.com/assets-manager/phpdoc/
license: GPL-3.0

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title.html
logo: false
paginate: 10
baseurl: /assets-manager
domain_name: 'http://atelierspierrot.github.com'

# Details for the RSS feed generator
url:            'http://atelierspierrot.github.com/assets-manager'
author:         'Les Ateliers Pierrot'
author_url:     'http://www.ateliers-pierrot.fr/'