var tree = [["[Global Namespace]",,"",
                [["SplClassLoader","SplClassLoader.html","",
                [        ]]        ]],["AssetsManager","AssetsManager.html","",
                [["Composer","AssetsManager\/Composer.html","",
                [["Autoload","AssetsManager\/Composer\/Autoload.html","",
                [["AbstractAutoloadGenerator","AssetsManager\/Composer\/Autoload\/AbstractAutoloadGenerator.html","",
                [        ]],["AssetsAutoloadGenerator","AssetsManager\/Composer\/Autoload\/AssetsAutoloadGenerator.html"," < AbstractAutoloadGenerator",
                [        ]]        ]],["Installer","AssetsManager\/Composer\/Installer.html","",
                [["AssetsInstaller","AssetsManager\/Composer\/Installer\/AssetsInstaller.html"," < LibraryInstaller",
                [        ]],["AssetsInstallerInterface","AssetsManager\/Composer\/Installer\/AssetsInstallerInterface.html","",
                [        ]]        ]],["Util","AssetsManager\/Composer\/Util.html","",
                [["Filesystem","AssetsManager\/Composer\/Util\/Filesystem.html"," < Filesystem",
                [        ]]        ]],["Dispatch","AssetsManager\/Composer\/Dispatch.html","",
                [        ]]        ]],["Config","AssetsManager\/Config.html","",
                [["ConfiguratorInterface","AssetsManager\/Config\/ConfiguratorInterface.html","",
                [        ]],["DefaultConfig","AssetsManager\/Config\/DefaultConfig.html","",
                [        ]]        ]],["Package","AssetsManager\/Package.html","",
                [["PresetAdapter","AssetsManager\/Package\/PresetAdapter.html","",
                [["Css","AssetsManager\/Package\/PresetAdapter\/Css.html","",
                [        ]],["Javascript","AssetsManager\/Package\/PresetAdapter\/Javascript.html","",
                [        ]],["Requirement","AssetsManager\/Package\/PresetAdapter\/Requirement.html","",
                [        ]]        ]],["AbstractAssetsPackage","AssetsManager\/Package\/AbstractAssetsPackage.html","",
                [        ]],["AssetsPackage","AssetsManager\/Package\/AssetsPackage.html"," < AbstractAssetsPackage",
                [        ]],["AssetsPackageInterface","AssetsManager\/Package\/AssetsPackageInterface.html","",
                [        ]],["AssetsPresetInterface","AssetsManager\/Package\/AssetsPresetInterface.html","",
                [        ]],["Preset","AssetsManager\/Package\/Preset.html","",
                [        ]],["PresetAdapterInterface","AssetsManager\/Package\/PresetAdapterInterface.html","",
                [        ]]        ]],["Config","AssetsManager\/Config.html","",
                [        ]],["Error","AssetsManager\/Error.html","",
                [        ]],["Loader","AssetsManager\/Loader.html"," < AbstractAssetsPackage",
                [        ]]        ]]        ]

